### ISSUE TITLE
__init__() got an unexpected keyword argument 'low_memory'

### ISSUE THREAD

**Issue by ZhaoxiangSimonCai** [broadinstitute/celligner#4]
Hi team,

Thank you for developing this powerful tool. We are trying to use it for our own data but it hit this error when I tried to run the .transform().

> reducing dimensionality...
> doing differential expression analysis on the clusters..
> running differential expression on 27 clusters
> running limmapy on the samples
> you need to have R installed with the limma library installed
> 3.5.3
> there is 0.283 overlap between the fit and transform dataset in their most variable genes
> doing cPCA..

> TypeError                                 Traceback (most recent call last)
/var/folders/7r/70gsq7hd1p5f6d8cgzf0ftb80000gr/T/ipykernel_43417/3434172114.py in <module>
----> 1 _ = my_alligner.transform(X_val_one_percentile)

> ~/anaconda3/envs/local/lib/python3.9/site-packages/celligner/__init__.py in transform(self, X_pression, annotations, only_transform, _rerun, _doCPCA, recompute_contamination)
    580                     # TODO: try the automated version, (select the best alpha above 1?)
    581                     self.cpca_loadings = (
--> 582                         CPCA(
    583                             standardize=False,
    584                             n_components=self.cpca_ncomp,

TypeError: __init__() got an unexpected keyword argument 'low_memory'

Looking at the code, it passes this argument when creating the CPCA instance.
https://github.com/broadinstitute/celligner/blob/master/celligner/__init__.py#L585

However, checking the contrastive package, it seems it doesn't accept this argument even for their latest version on Github.
https://github.com/abidlabs/contrastive/blob/master/contrastive/__init__.py#L44

Could you please advise what I should do in this case? Thank you very much in advance.

**Comment by jkobject** [comment]
Hello,

The issue here is that you are using their package whereas celligner is using a modification of that package:

<img width="1366" alt="Screenshot 2022-08-15 at 11 55 53" src="https://user-images.githubusercontent.com/17239533/184670201-161587d2-f9cc-499b-ac8a-1ac0798650e5.png">

you need to pull the submodules.

**Comment by jkobject** [comment]
So right now you would want to remove your CPCA installation and install the version listed in the submodule of this project instead.

I just made a commit to debug this problem from the regular installation of celligner.

**Comment by ZhaoxiangSimonCai** [comment]
Thanks a lot for your help! I have now resolved the issue and run it successfully.
